# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4766ed8db1d78fd4d1c3b431e2e8f7b604551ba64414b35d55e9c1cc29228bae9ac64fbf74a51c10ef3ddf512dc2ba03a43b2b9b549841463aa25244dd308dba

test:
  secret_key_base: 4c76e7284e5b4bc2d407911e6fbe74cacecca254a436f48e34d52e87120b33c71b03f37eb1a8941997cf943f817f8e97ae8e41093b15bb7921226273e5ea4a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
